name: workflow

on: [push, pull_request]

jobs:
    frontend-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Frontend tests
              run: |
                  cd frontend
                  npm install
                  npm run test:all

    backend-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Backend tests
              run: |
                  cd backend
                  npm install
                  npm run test:all
